let msg = "     hello     ";
console.log("the original str is ", msg);
console.log("the trimmed str is ", msg.trim());
console.log("please set a password");
//let pass = prompt("Enter your password");
//console.log("the password is ", pass.trim());
console.log("the index of h in str is", msg.indexOf("h"));
let str = "IloveCG";
console.log("the original str is", str);
console.log("the Sliced str is",str.slice(1,4));
console.log("the replaced str is", str.replace("love", "am"));